version: 2.1

description: Automates releases to Hackage

executors:
  default:
    docker:
      - image: quay.io/haskell_works/ghc-8.4.4:latest

commands:
  upload:
    description: Uploads package to Hackage
    parameters:
      server:
        description: Hackage server
        type: string
      username:
        description: Hackage username
        type: string
      password:
        description: Hackage password
        type: string
      publish:
        description: Publish the release. Without this flag a candidate will be created.
        type: boolean
        default: false
    steps:
      - prepare-release
      - run:
          name: Publishing on Hackage
          command: |
            for PACKAGE_TARBALL in $(find ./build/sdist/ -name "*.tar.gz"); do
              PACKAGE_NAME=$(basename ${PACKAGE_TARBALL%.*.*})

              if [ -z "<<# parameters.publish >>true<</ parameters.publish >>" ];
                then TARGET_URL="<< parameters.server >>/packages/candidates";
                else TARGET_URL="<< parameters.server >>/packages/upload";
              fi

              HACKAGE_STATUS=$(curl --silent --head -w %{http_code} -XGET --anyauth --user << parameters.username >>:<< parameters.password >> << parameters.server >>/package/$PACKAGE_NAME -o /dev/null)
              if [ "$HACKAGE_STATUS" = "404" ]; then

                echo "Uploading $PACKAGE_NAME to $TARGET_URL"

                curl -X POST -f --user << parameters.username >>:<< parameters.password >> $TARGET_URL -F "package=@$PACKAGE_TARBALL"
                echo "Uploaded $PACKAGE_NAME"
              else
                echo "Package $PACKAGE_NAME" already exists on Hackage.
              fi
            done

  prepare-release:
    description:
      Prepares a release. Creates a tarball, checks if the release is needed,
      and sets PACKAGE_TARBALL and PACKAGE_NAME env variables.
    steps:
      - run:
          name: Preparing the release
          command: |
              PROJECT_DIR=$PWD
              mkdir -p $PROJECT_DIR/build/sdist
              for i in $(git ls-files | grep .cabal); do
                cd $PROJECT_DIR && cd `dirname $i`
                cabal check && cabal new-sdist -o $PROJECT_DIR/build/sdist
              done;

jobs:
  upload:
    description: Uploads package to Hackage
    parameters:
      executor:
        type: executor
        default: default
      server:
        description: Hackage server
        type: string
        default: ${HACKAGE_SERVER:-http://hackage.haskell.org}
      username:
        description: Hackage username
        type: string
        default: ${HACKAGE_USER}
      password:
        description: Hackage password
        type: string
        default: ${HACKAGE_PASS}
      publish:
        description: Publish the release. Without this flag a candidate will be created.
        type: boolean
        default: false
      after-checkout:
        description: Optional steps to execute after checking out code
        type: steps
        default: []
      after-upload:
        description: Optional steps to execute after uploading is done
        type: steps
        default: []
    executor: << parameters.executor >>
    steps:
      - checkout
      - when:
          condition: << parameters.after-checkout >>
          steps: << parameters.after-checkout >>
      - upload:
          server: << parameters.server >>
          username: << parameters.username >>
          password: << parameters.password >>
          publish: << parameters.publish >>
      - when:
          condidion: << parameters.after-upload >>
          steps: << parameters.after-upload >>
